[project]
name = "gr_tools"
authors = [
    { name = "Agile Shift", email = "contacto@gruporeal.org"}
]
description = "Custom configurations, tweaks and Tools for ERPNext and Frappe"
requires-python = ">=3.14"
readme = "README.md"
dynamic = ["version"]

dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
typing-modules = ["frappe.types.DF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
